config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: {sign_in: "login", sign_out: "logout", sign_up: 'register'}
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
  end
end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
   <div class="inner">
      <p class="app-footer"><%= copyright_generator %></p>
   </div>
 </div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner-1">
		<h3 class="masthead-brand">McKaid C. Gustafson</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>


<!-- if nav has issues add clearfix to masthead  -->

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p class = "cg-blog">
  <%= copyright_generator %>
  </p>

  <p>
    <a href="#", class="Back_to_top">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">

    <span>
    <%= link_to 'Write A New Blog', new_blog_path, class: 'btn btn-md btn-info admin-nav' if logged_in?(:site_admin) %>
    </span>
    
    <span>
    <%= link_to "Topics", topics_path, class: 'btn btn-md btn-info admin-nav' %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav navbar-left">
        <%= nav_helper 'nav-link', 'li' %>
        <%= login_helper 'nav-link' %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4 class= "sidebar-title">Favorite Language</h4>
    <hr>
    <p class= "sidebar-title"><%= image_tag "ruby-logo.png", width: 130, height: 130, alt: "avatar", class: 'img' %></p>
      <div class= 'sidebar-title'>Ruby</div>
  </div>


  <%= source_helper("alert alert-info blog-sidebar-source") %>

  <div class="sidebar-module">
    <h4 class= "sidebar-title">Topics</h4>
    <hr>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic), class: 'btn btn-secondary btn-block topic-links'%></p>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4 class= "sidebar-title">Elsewhere</h4>
    <hr>
    <ol class="list-unstyled social-links">
      <li class="icons"><a href="https://github.com/" target= "_blank"><%= fa_icon "github" %></a></li>
      <li class="icons"><a href="https://www.instagram.com/?hl=en" target= "_blank"><%= fa_icon "instagram" %></a></li>
      <li class="icons"><a href="https://www.facebook.com/" target= "_blank"><%= fa_icon "facebook" %></a></li>
      <li class="icons"><a href="https://twitter.com/" target= "_blank"><%= fa_icon "twitter" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
<%= link_to "Home", root_path %>
<%= link_to "About-me", about_me_path %>
<%= link_to "Contact", contact_path %>
<%= link_to "Blog", blogs_path %>
<%= link_to "Portfolio", portfolios_path %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right ">
     <%= link_to "View All Portfolio Items", portfolios_path, class: "portfolio-link" %> /
      <a href="#" class= "portfolio-link">Back to top</a>
      </p>
       <p>
    	<%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
<div class="container">
  <h1 class="jumbotron-heading">Portfolio</h1>
  <p class="lead text-muted"></p>
  <hr>
  <p>
    <%= link_to 'Home', root_path, class: 'btn btn-secondary button-link' %>
    <%= link_to 'My Blogs', blogs_path, class: 'btn btn-secondary button-link' %>
  </p>
</div>
</section>

app/views/shared/_portfolio_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class= "port-nav">
      <ul class="navbar-nav mr-auto ul-nav-port">
        <%= nav_helper 'nav-link', 'li' %>
        <%= login_helper 'nav-link' %>
      </ul>
    </div>
    </div>
  </div>
</nav>